# .github/workflows/preview.yml
name: Preview static site build

on:
  push:
    branches-ignore: ["main"] # Run on all branches except main
  workflow_dispatch:

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Simulate site build
        run: |
          mkdir output
          # Example build step – replace this with your actual build logic
          cp -r * output/
          echo "<!-- Preview site built from branch ${{ github.ref_name }} -->" >> output/index.html

      - name: Upload preview artifact
        uses: actions/upload-artifact@v4
        with:
          name: preview-site
          path: output
